# Generated by Django 5.2.6 on 2025-10-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0003_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Duration (months) granted by this payment'),
        ),
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('price_minor', models.PositiveIntegerField(help_text='Price in minor units (paise/cents)')),
                ('duration_months', models.PositiveSmallIntegerField(default=1, help_text='Duration (months) applied after payment')),
            ],
            options={
                'verbose_name': 'Plan pricing',
                'verbose_name_plural': 'Plan pricing',
                'unique_together': {('plan_type', 'currency')},
            },
        ),
    ]
