# Generated by Django 5.2.6 on 2025-10-20 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0004_payment_duration_months_planpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Extra duration in days (offers)', null=True),
        ),
        migrations.CreateModel(
            name='LimitedTimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=3)),
                ('price_minor', models.PositiveIntegerField(help_text='Offer price in minor units (paise/cents)')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Offer duration in days (e.g., 7)')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Limited-time offer',
                'verbose_name_plural': 'Limited-time offers',
                'indexes': [models.Index(fields=['plan_type', 'currency', 'is_active', 'starts_at', 'ends_at'], name='checker_app_plan_ty_91f521_idx')],
            },
        ),
    ]
