# Generated by Django 5.2.6 on 2025-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0005_payment_duration_days_limitedtimeoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitedtimeoffer',
            options={},
        ),
        migrations.AlterField(
            model_name='limitedtimeoffer',
            name='price_minor',
            field=models.PositiveIntegerField(help_text='Offer price in minor units'),
        ),
    ]
