# Generated by Django 5.2.6 on 2025-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0006_alter_limitedtimeoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeoffer',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='limitedtimeoffer',
            name='duration_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='limitedtimeoffer',
            name='price_minor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
